import Head from "next/head";
import ColorChanger from "../components/ColorChanger";
import Counter from "../components/Counter";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Use Context Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto my-5">
        <h1 className="text-4xl text-center">Use Context - Template</h1>
        <div className="grid mt-10 md:mt-52 md:grid-cols-2">
          <Counter />
          <ColorChanger />
        </div>
      </main>
    </div>
  );
}
